name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  lint-build:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install invoke black flake8
      - name: Lint
        run: |
            invoke lint
            invoke checkformat

  test-builds:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Python versions
          - name: Linux py37
            os: ubuntu-latest
            pyversion: '3.7'
          - name: Linux py38
            os: ubuntu-latest
            pyversion: '3.8'
          - name: Linux py39
            os: ubuntu-latest
            pyversion: '3.9'
          - name: Linux py310
            os: ubuntu-latest
            pyversion: '3.10'
          - name: Linux py312
            os: ubuntu-latest
            pyversion: '3.12'
          - name: Linux pypy
            os: ubuntu-latest
            pyversion: 'pypy3.9'
          # OS's
          - name: Linux py311
            os: ubuntu-latest
            pyversion: '3.11'
          - name: Windows py311
            os: windows-latest
            pyversion: '3.11'
          - name: MacOS py311
            os: macos-latest
            pyversion: '3.11'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install psutil
            pip install invoke pytest pytest-cov
            invoke get-ffmpeg-binary
            pip install .
            rm -r ./imageio_ffmpeg
      - name: Test with pytest
        run: |
            python -c "import sys; print(sys.version, '\n', sys.prefix)";
            python -c 'import imageio_ffmpeg; print(imageio_ffmpeg.get_ffmpeg_version())'
            pytest tests -v --cov=imageio_ffmpeg --cov-report=term
